import type {
  CreateTargetInput,
  DashboardStats,
  EventItem,
  HistoryFilter,
  HistoryPage,
  ImportResult,
  MonitoringStatus,
  NotificationConfig,
  PingTestResult,
  Settings,
  Target,
  TargetDetails,
  TargetGroup,
  UpdateTargetInput,
} from "@/types";
import {
  CreateGroup,
  CreateTarget,
  DeleteGroup,
  DeleteTarget,
  ExportTargets,
  GetDashboardStats,
  GetEvents,
  GetMonitoringStatus,
  GetNotificationConfig,
  GetSettings,
  GetTargetDetails,
  GetTargetHistory,
  GetTargets,
  ImportTargets,
  ListGroups,
  MinimizeToTray,
  MuteNotifications,
  MuteTarget,
  PauseAll,
  QuitApp,
  SetTargetEnabled,
  StartMonitoring,
  StopMonitoring,
  TestNotification,
  TestPing,
  UpdateGroup,
  UpdateNotificationConfig,
  UpdateSettings,
  UpdateTarget,
} from "@wailsjs/go/main/App";

export const api = {
  getTargets: () => GetTargets() as Promise<Target[]>,
  createTarget: (input: CreateTargetInput) => CreateTarget(input as never) as Promise<Target>,
  updateTarget: (id: string, input: UpdateTargetInput) => UpdateTarget(id, input as never) as Promise<Target>,
  deleteTarget: (id: string) => DeleteTarget(id) as Promise<void>,
  setTargetEnabled: (id: string, enabled: boolean) => SetTargetEnabled(id, enabled) as Promise<Target>,
  muteTarget: (id: string, seconds: number) => MuteTarget(id, seconds) as Promise<Target>,
  testPing: (host: string, timeout: number) => TestPing(host, timeout) as Promise<PingTestResult>,
  getHistory: (filter: HistoryFilter) => GetTargetHistory(filter as never) as Promise<HistoryPage>,
  getDashboardStats: () => GetDashboardStats() as Promise<DashboardStats>,
  getTargetDetails: (id: string) => GetTargetDetails(id) as Promise<TargetDetails>,
  getSettings: () => GetSettings() as Promise<Settings>,
  updateSettings: (s: Settings) => UpdateSettings(s as never) as Promise<Settings>,
  muteNotifications: (seconds: number) => MuteNotifications(seconds) as Promise<Settings>,
  listGroups: () => ListGroups() as Promise<TargetGroup[]>,
  createGroup: (name: string, color: string) => CreateGroup(name, color) as Promise<TargetGroup>,
  updateGroup: (id: string, name: string, color: string) => UpdateGroup(id, name, color) as Promise<TargetGroup>,
  deleteGroup: (id: string) => DeleteGroup(id) as Promise<void>,
  getNotificationConfig: (provider: string) => GetNotificationConfig(provider) as Promise<NotificationConfig>,
  updateNotificationConfig: (c: NotificationConfig) => UpdateNotificationConfig(c as never) as Promise<NotificationConfig>,
  testNotification: (provider: string) => TestNotification(provider) as Promise<void>,
  importTargets: (payload: string, format: string) => ImportTargets(payload, format) as Promise<ImportResult>,
  exportTargets: (format: string) => ExportTargets(format) as Promise<string>,
  startMonitoring: () => StartMonitoring() as Promise<void>,
  stopMonitoring: () => StopMonitoring() as Promise<void>,
  pauseAll: () => PauseAll() as Promise<void>,
  getMonitoringStatus: () => GetMonitoringStatus() as Promise<MonitoringStatus>,
  getEvents: (filter: { targetId?: string; type?: string; limit?: number; offset?: number }) =>
    GetEvents(filter as never) as Promise<EventItem[]>,
  minimizeToTray: () => MinimizeToTray() as Promise<void>,
  quitApp: () => QuitApp() as Promise<void>,
};
