// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {domain} from '../models';

export function CheckForUpdate():Promise<updater.Info>;

export function CreateGroup(arg1:string,arg2:string):Promise<domain.TargetGroup>;

export function CreateTarget(arg1:domain.CreateTargetInput):Promise<domain.Target>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteTarget(arg1:string):Promise<void>;

export function ExportTargets(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDashboardStats():Promise<domain.DashboardStats>;

export function GetEvents(arg1:domain.EventFilter):Promise<Array<domain.Event>>;

export function GetMonitoringStatus():Promise<domain.MonitoringStatus>;

export function GetNotificationConfig(arg1:string):Promise<domain.NotificationConfig>;

export function GetSettings():Promise<domain.Settings>;

export function GetTarget(arg1:string):Promise<domain.Target>;

export function GetTargetDetails(arg1:string):Promise<domain.TargetDetails>;

export function GetTargetHistory(arg1:domain.HistoryFilter):Promise<domain.HistoryPage>;

export function GetTargets():Promise<Array<domain.Target>>;

export function ImportTargets(arg1:string,arg2:string):Promise<domain.ImportResult>;

export function InstallUpdate():Promise<void>;

export function ListGroups():Promise<Array<domain.TargetGroup>>;

export function MinimizeToTray():Promise<void>;

export function MuteNotifications(arg1:number):Promise<domain.Settings>;

export function MuteTarget(arg1:string,arg2:number):Promise<domain.Target>;

export function OpenReleasePage():Promise<void>;

export function PauseAll():Promise<void>;

export function QuitApp():Promise<void>;

export function SetTargetEnabled(arg1:string,arg2:boolean):Promise<domain.Target>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function TestNotification(arg1:string):Promise<void>;

export function TestPing(arg1:string,arg2:number):Promise<domain.PingTestResult>;

export function UpdateGroup(arg1:string,arg2:string,arg3:string):Promise<domain.TargetGroup>;

export function UpdateNotificationConfig(arg1:domain.NotificationConfig):Promise<domain.NotificationConfig>;

export function UpdateSettings(arg1:domain.Settings):Promise<domain.Settings>;

export function UpdateTarget(arg1:string,arg2:domain.UpdateTargetInput):Promise<domain.Target>;
