// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTarget(arg1) {
  return window['go']['main']['App']['CreateTarget'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function ExportTargets(arg1) {
  return window['go']['main']['App']['ExportTargets'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetEvents(arg1) {
  return window['go']['main']['App']['GetEvents'](arg1);
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function GetNotificationConfig(arg1) {
  return window['go']['main']['App']['GetNotificationConfig'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTarget(arg1) {
  return window['go']['main']['App']['GetTarget'](arg1);
}

export function GetTargetDetails(arg1) {
  return window['go']['main']['App']['GetTargetDetails'](arg1);
}

export function GetTargetHistory(arg1) {
  return window['go']['main']['App']['GetTargetHistory'](arg1);
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function ImportTargets(arg1, arg2) {
  return window['go']['main']['App']['ImportTargets'](arg1, arg2);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetTargetEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTargetEnabled'](arg1, arg2);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestNotification(arg1) {
  return window['go']['main']['App']['TestNotification'](arg1);
}

export function TestPing(arg1, arg2) {
  return window['go']['main']['App']['TestPing'](arg1, arg2);
}

export function UpdateNotificationConfig(arg1) {
  return window['go']['main']['App']['UpdateNotificationConfig'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTarget(arg1, arg2) {
  return window['go']['main']['App']['UpdateTarget'](arg1, arg2);
}
