// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateMaintenanceWindow(arg1) {
  return window['go']['main']['App']['CreateMaintenanceWindow'](arg1);
}

export function CreateTarget(arg1) {
  return window['go']['main']['App']['CreateTarget'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteMaintenanceWindow(arg1) {
  return window['go']['main']['App']['DeleteMaintenanceWindow'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function ExportTargets(arg1) {
  return window['go']['main']['App']['ExportTargets'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetEvents(arg1) {
  return window['go']['main']['App']['GetEvents'](arg1);
}

export function GetIncidentReport(arg1, arg2) {
  return window['go']['main']['App']['GetIncidentReport'](arg1, arg2);
}

export function GetIncidents(arg1) {
  return window['go']['main']['App']['GetIncidents'](arg1);
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function GetNotificationConfig(arg1) {
  return window['go']['main']['App']['GetNotificationConfig'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTarget(arg1) {
  return window['go']['main']['App']['GetTarget'](arg1);
}

export function GetTargetDetails(arg1) {
  return window['go']['main']['App']['GetTargetDetails'](arg1);
}

export function GetTargetHistory(arg1) {
  return window['go']['main']['App']['GetTargetHistory'](arg1);
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function ImportTargets(arg1, arg2) {
  return window['go']['main']['App']['ImportTargets'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListMaintenanceWindows() {
  return window['go']['main']['App']['ListMaintenanceWindows']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MuteNotifications(arg1) {
  return window['go']['main']['App']['MuteNotifications'](arg1);
}

export function MuteTarget(arg1, arg2) {
  return window['go']['main']['App']['MuteTarget'](arg1, arg2);
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetTargetEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTargetEnabled'](arg1, arg2);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestNotification(arg1) {
  return window['go']['main']['App']['TestNotification'](arg1);
}

export function TestPing(arg1, arg2) {
  return window['go']['main']['App']['TestPing'](arg1, arg2);
}

export function TestProbe(arg1) {
  return window['go']['main']['App']['TestProbe'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateMaintenanceWindow(arg1, arg2) {
  return window['go']['main']['App']['UpdateMaintenanceWindow'](arg1, arg2);
}

export function UpdateNotificationConfig(arg1) {
  return window['go']['main']['App']['UpdateNotificationConfig'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTarget(arg1, arg2) {
  return window['go']['main']['App']['UpdateTarget'](arg1, arg2);
}
